### ISSUE TITLE
Configuration Problem

### ISSUE THREAD

**Issue by sparrcity** [DavD729/AppleTreesRev#2]
Hello, I seem to be having an issue with the mod. It's pretty small, but it does leave out a feature stated within the description

Version using: 1.16.5

Platform: Forge

Okay, so, the problem is with the configuration of the mod. I cannot seem to configure the mod to enable the golden apple trees or the notch apple recipe.

I don't know if perhaps any mod listed below could be the problem, or maybe I downloaded the wrong file. Is there anything I can do?

I am using a few other mods with this, so idk if this is part of the problem, but I will list them in case!

Quark (Plus AutoRegLib)
Dynamic Surroundings
Ice and Fire: Dragons (Plus Citadel)
Project Vibrant Journeys
Biomes O' Plenty
Environmental (Plus Abnormal' s Core)
Optifine
Wyrmroost
Exotic Birds

**Comment by DavD729** [comment]
Do you know the forge version that are you using?
(This is just to Check) :)

**Comment by DavD729** [comment]
Hi Again! :)

I Couldn't replicate the problem, the first i have in mind is check Your Forge Version (Forge 1.16.5 - 36.1.0+)
Also Check This mod File (AppleTreesRev-Forge-1.16.5-v1.2+)

If this is Allright, try Removing the actual Config File of my mod, then Run the Game Again to Generate Another one,
I Don't really know if the Config File Broke for some Reason, but for me is Working, even With all of Your Mods

I Hope it Works ;)
