### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by CCCClear** [DavD729/AppleTreesRev#4]
In the latest 1.16 release, I discovered a mod conflict with the Charm mod.
I can only detect two conflicting mods, but I don't know why.
This is my error report. I hope it helps you.
[crash.txt](https://github.com/DavD729/AppleTreesRev/files/6829967/crash.txt)

**Comment by DavD729** [comment]
Sorry for so much time, i'll check what kind of incompatibility happen

**Comment by CCCClear** [comment]
Creators always have their own schedule, and I appreciate you trying to solve this problem, since I always want to play with the latest version.

**Comment by DavD729** [comment]
I confirm the incompatibility problem and it will be resolved in the next version (v2.2)
Thanks for the FeedBack <3
