### ISSUE TITLE
   Apple Trees Revived (appletreesrev) encountered an error during the load_registries event phase

### ISSUE THREAD

**Issue by epicyeeto** [DavD729/AppleTreesRev#5]
I keep on trying to make a server with apple trees revived but it keeps on crashing and saying this 

-- MOD appletreesrev --
Details:
	Mod File: AppleTreesRev-Forge-1.16.5-v2.1.jar
	Failure message: Apple Trees Revived (appletreesrev) encountered an error during the error event phase
		java.lang.NoClassDefFoundError: Could not initialize class dav.mod.lists.BlockList
	Mod Version: 2.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoClassDefFoundError: Could not initialize class dav.mod.lists.BlockList

**Comment by DavD729** [comment]
I'll be checking what happen here

**Comment by DavD729** [comment]
I confirm the existence of the Server side problem and will be solved on the next Version (v2.2)
Thanks for the FeedBack <3

**Comment by epicyeeto** [comment]
ok thank you
