### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by deftesthawk** [DavD729/AppleTreesRev#7]
Could you add more configs for example dungeon loot spawn chances for the golden apple, an option for disabling it altogether, and an option to disable bonemeal working on them. As I tried using this in my mod pack but it was too easy to get golden apples and took away the incentive for people to use other food mods

**Comment by DavD729** [comment]
Let me check what can i do

**Comment by deftesthawk** [comment]
Thanks :)

**Comment by DavD729** [comment]
Bonemeal Options has been Added to the Game, I'll be working on Lootable Chests Options
